---
name: Update add_aliases.sh
on:
  push:
    branches:
      - main

jobs:
  update_add_aliases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Update Aliases
        run: chmod +x update_aliases.sh && ./update_aliases.sh

      - name: Compare add_aliases.sh.temp with add_aliases.sh
        id: diff
        run: diff add_aliases.sh.temp add_aliases.sh
        continue-on-error: true

      - name: Replace add_aliases.sh with add_aliases.sh.temp
        if: steps.diff.outcome != 'success'
        run: mv add_aliases.sh.temp add_aliases.sh

      - name: commit updated File
        if: steps.diff.outcome != 'success'
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: add_aliases.sh
          commit: --signoff
          message: Updatet add_aliases to match changes in .gitconfig
